package Estadistica;


import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author R2D2
 */
public class V_ModeloUniversal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public V_ModeloUniversal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cantDatos = new javax.swing.JLabel();
        cantInterv = new javax.swing.JLabel();
        Amplitud = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        range = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnVentanaInicio = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ARCHIVO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        jButton1.setFont(new java.awt.Font("Bebas", 0, 11)); // NOI18N
        jButton1.setText("Abrir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        cantDatos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cantDatos.setForeground(new java.awt.Color(255, 255, 255));
        cantDatos.setText("n :");
        getContentPane().add(cantDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, -1, -1));

        cantInterv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cantInterv.setForeground(new java.awt.Color(255, 255, 255));
        cantInterv.setText("m :");
        getContentPane().add(cantInterv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, -1, -1));

        Amplitud.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Amplitud.setForeground(new java.awt.Color(255, 255, 255));
        Amplitud.setText("C :");
        getContentPane().add(Amplitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 126, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Y'i-1", "Y'i", "Yi", "ni", "hi", "Ni", "Hi"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, 552, 180));

        range.setForeground(new java.awt.Color(255, 255, 255));
        range.setText("RANGO: ");
        getContentPane().add(range, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 106, -1, -1));

        jButton2.setFont(new java.awt.Font("Bebas", 0, 11)); // NOI18N
        jButton2.setText("Calcular        Varianza");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 21, -1, -1));

        btnVentanaInicio.setFont(new java.awt.Font("Bebas", 0, 11)); // NOI18N
        btnVentanaInicio.setText("Volver");
        btnVentanaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentanaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wpid-Black-Background-Wood-Clean-black-wallpaper-hd.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -60, 690, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            obtenerDatos();
            definirParametros();
            generarTabla();
            jTable1.enable();
            //Estadistica.getFrecuenciaR(datos, )
        } catch (Exception ex) {
            Logger.getLogger(V_ModeloUniversal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "Ha ocurrido un error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTable1.getModel().getRowCount() > 0) {
            VarianzaV = new V_Varianza(this);
            VarianzaV.setResizable(false);
            VarianzaV.setLocationRelativeTo(this);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnVentanaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaInicioActionPerformed
        VentanaInicio vInicio = new VentanaInicio();
        vInicio.setVisible(true);
        vInicio.setSize(575,330);
        vInicio.setResizable(false);
        vInicio.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_btnVentanaInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    private javax.swing.JFileChooser buscador;
    private File archivo;
    private Convertidor convertidor;
    private ArrayList<Double> datos, clase;
    private ArrayList<Integer> fRel;
    private int n, m;
    private double c, rUp, rDown;
    private V_Varianza VarianzaV;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amplitud;
    private javax.swing.JToggleButton btnVentanaInicio;
    private javax.swing.JLabel cantDatos;
    private javax.swing.JLabel cantInterv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel range;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Double> obtenerDatos() throws Exception {
        try {
            //Buscar el archivo y convertir sus datos en un arreglo numerico
            buscador = new JFileChooser();
            buscador.showOpenDialog(null);
            archivo = buscador.getSelectedFile();
            convertidor = new Convertidor(archivo);
            datos = convertidor.getDatos();

            return datos;
        } catch (Exception ex) {
            throw new Exception("No se pudo acceder al archivo o no existe");
        }
    }

    private void definirParametros() {
        String s;
        //Obtener la cantidad de datos y mostrarla en la GUI
        n = datos.size();
        s = "n : " + n;
        cantDatos.setText(s);

        //Definir la cantidad de intervalos que se utilizaran 
        s = "m : " + Convertidor.round(Estadistica.getIntervalos(n));
        m = Estadistica.getM();
        s += " -> " + m;
        cantInterv.setText(s); //mostrar la cant. intervalos en la GUI

        //obtener el rango de los datos por si no estan ordenados
        rUp = Estadistica.getMax(datos);
        rDown = Estadistica.getMin(datos);
        s = "Rango:  " + rDown + " - " + rUp;
        range.setText(s); //Mostratlo en la GUI

        //obtener valor de amplitud(C)
        c = Estadistica.getAmplitud(rDown, rUp);
        s = "C : " + c;
        Amplitud.setText(s);

    }

    private void generarTabla() {
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        if (tabla.getRowCount() > 0) {
            int m = tabla.getRowCount();
            for (int i = 0; i < m; i++) {
                tabla.removeRow(0);
            }
        }
        double tmp, tmp2, fa, fat;
        int fr, frt;
        clase = new ArrayList<Double>();
        fRel = new ArrayList<Integer>();
        //inicializacion de las variables
        Vector v = new Vector();
        frt = 0;
        fat = 0;
        tmp = rDown;
        tmp2 = tmp + c;
        fr = Estadistica.GetFRelativa(tmp, tmp2, datos);
        fa = Estadistica.getFAbsoluta(tmp, tmp2, datos);
        frt += fr;
        fat += fa;
        //primer fila de datos
        v.add(tmp);
        v.add(tmp2);
        v.add((tmp + tmp2) / 2);
        clase.add((tmp + tmp2) / 2);
        v.add(fr);
        fRel.add(fr);
        v.add(fa);
        v.add(frt);
        v.add(fat);
        tabla.addRow(v);
        //el resto de filas
        for (int i = 0; i < m - 1; i++) {
            v = new Vector();
            tmp += c;
            tmp2 += c;
            fr = Estadistica.GetFRelativa(tmp, tmp2, datos);
            fa = Estadistica.getFAbsoluta(tmp, tmp2, datos);
            frt += fr;
            fat += fa;
            v.add(tmp);
            v.add(tmp2);
            v.add((tmp + tmp2) / 2);
            clase.add((tmp + tmp2) / 2);
            v.add(fr);
            fRel.add(fr);
            v.add(fa);
            v.add(frt);
            v.add(fat);
            tabla.addRow(v);
        }
        v = new Vector();
        v.add("-");
        v.add("-");
        v.add("-");
        v.add(frt);
        v.add(fat);
        v.add("-");
        v.add("-");
        tabla.addRow(v);
        //asignacion del modelo de la tabla a la tabla de la GUI
        jTable1.setModel(tabla);
    }
    
    public ArrayList<Double> getYClase(){
        return clase;
    }
    
    public ArrayList<Integer> getNi(){
        return fRel;
    }
}
