package Estadistica;


import org.apache.poi.hdgf.pointers.Pointer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModeloU = new javax.swing.JToggleButton();
        btnPoisson = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModeloU.setFont(new java.awt.Font("Bebas", 0, 11)); // NOI18N
        btnModeloU.setForeground(new java.awt.Color(51, 51, 51));
        btnModeloU.setText("Modelo       Universal");
        btnModeloU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModeloUActionPerformed(evt);
            }
        });
        getContentPane().add(btnModeloU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 60));

        btnPoisson.setFont(new java.awt.Font("Bebas", 0, 11)); // NOI18N
        btnPoisson.setForeground(new java.awt.Color(51, 51, 51));
        btnPoisson.setText("Probabilidad       Poisson");
        btnPoisson.setPreferredSize(new java.awt.Dimension(125, 23));
        btnPoisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoissonActionPerformed(evt);
            }
        });
        getContentPane().add(btnPoisson, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 150, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sin título-3.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 102, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 230, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sin título-2.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 102, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 230, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wpid-Black-Background-Wood-Clean-black-wallpaper-hd.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModeloUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModeloUActionPerformed
        V_ModeloUniversal vU = new V_ModeloUniversal();
        vU.setVisible(true);
        vU.setSize(576,379);
        vU.setResizable(false);
        vU.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_btnModeloUActionPerformed

    private void btnPoissonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoissonActionPerformed
        V_Poisson vP = new V_Poisson();
        vP.setVisible(true);
        vP.setSize(620,339);
        vP.setResizable(false);
        vP.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_btnPoissonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
                new VentanaInicio().setSize(575,330);
                new VentanaInicio().setResizable(false);
                new VentanaInicio().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnModeloU;
    private javax.swing.JToggleButton btnPoisson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
